common: &common
  adapter: postgresql
  host: localhost
  min_messages: warning

development:
  <<: *common
  database: badgework_development

test: &test
  <<: *common
  database: badgework_test

production:
  <<: *common
  database: badgework_development